import type { DeployManifest } from "@appmarket/shared";

export interface RepoMapInput {
	repoName: string;
	tag: string;
	commit: string;
	entries: { path: string; type: string }[];
	/** Raw package.json and Wrangler config text, if present. */
	packageJson?: string;
	wranglerMain?: string;
	manifest: DeployManifest | null;
	hasAgentsMd: boolean;
}

const MAX_DEPTH = 4;
const MAX_LINES = 400;

/**
 * PRD G4: an orientation map for agents working on a fork: layout, entry point, scripts and
 * Cloudflare bindings, generated at publish and stored beside the version (not committed).
 */
export function buildRepoMap(input: RepoMapInput): string {
	const lines = [`# Repository map: ${input.repoName} ${input.tag}`, "", `Commit \`${input.commit}\`. Generated by appmarket.org at publish; read AGENTS.md first.`, ""];

	const scripts = parseScripts(input.packageJson);
	lines.push("## Start here", "");
	if (input.hasAgentsMd) lines.push("- `AGENTS.md`: the developer's guide for agents");
	if (input.wranglerMain) lines.push(`- Worker entry: \`${input.wranglerMain}\``);
	for (const [name, command] of Object.entries(scripts)) lines.push(`- \`npm run ${name}\`: \`${command}\``);
	lines.push("");

	if (input.manifest && input.manifest.resources.length > 0) {
		lines.push("## Cloudflare bindings", "");
		for (const r of input.manifest.resources) lines.push(`- \`${r.binding || "(none)"}\`: ${r.type}${r.name ? ` (${r.name})` : ""}`);
		if (input.manifest.secrets.length) lines.push(`- Secrets: ${input.manifest.secrets.map((s) => `\`${s}\``).join(", ")}`);
		lines.push("");
	}

	lines.push("## Layout", "", "```");
	const shown = input.entries.filter((e) => e.path.split("/").length <= MAX_DEPTH);
	for (const e of shown.slice(0, MAX_LINES)) {
		const depth = e.path.split("/").length - 1;
		const name = e.path.split("/").at(-1)!;
		lines.push(`${"  ".repeat(depth)}${name}${e.type === "tree" ? "/" : ""}`);
	}
	if (shown.length > MAX_LINES || shown.length < input.entries.length) lines.push(`… ${input.entries.length - Math.min(shown.length, MAX_LINES)} more entries not shown`);
	lines.push("```", "");
	return lines.join("\n");
}

function parseScripts(text: string | undefined): Record<string, string> {
	if (!text) return {};
	try {
		const pkg = JSON.parse(text) as { scripts?: Record<string, unknown> };
		return Object.fromEntries(Object.entries(pkg.scripts ?? {}).filter((e): e is [string, string] => typeof e[1] === "string"));
	} catch {
		return {};
	}
}
