// Regenerates src/og/assets.generated.ts from src/og/assets/*: fonts and images as base64, so
// they load the same way in the dev server and the deployed Worker.
import { readFileSync, writeFileSync } from "node:fs";

const files = { manrope800: "manrope-800.ttf", dmSans500: "dmsans-500.ttf", logo: "logo.png", cow: "cow.png" };
const lines = ["// Generated by scripts/og-assets.mjs from src/og/assets. Do not edit.", ""];
for (const [name, file] of Object.entries(files)) {
	lines.push(`export const ${name} = "${readFileSync(new URL(`../src/og/assets/${file}`, import.meta.url)).toString("base64")}";`);
}
writeFileSync(new URL("../src/og/assets.generated.ts", import.meta.url), `${lines.join("\n")}\n`);
